MapWebsite/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('', include('myapp.urls')),
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

myapp/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('adminpanel', views.index, name='index'),
    path('adminpanel/(?P<message>\d+)/$', views.index, name='index'),
    url(r'search',views.search_titles,name='search_titles'),
    path(r'getPlaces', views.serch_places, name='serch_places'),  #my code for search place
    url(r'admincall',views.admin_search_titles,name='admincall'),
    path('home/<int:num>/',views.result,name='result'),
    path('adminpanel/<int:num>/',views.admin_result,name='admin_result'),
    path('add_image_data/',views.add_image_data,name="add_image_data"),
    path('search_result',views.result,name='result'),
    path('upload/',views.upload,name='upload'),
    path('',views.home,name='home'),
    path('Insert_data/',views.Insert_data,name='Insert_data'),
    path('AllDatalist/',views.AllDatalist,name='AllDatalist'),
    path('AllDatalist/<int:num>/',views.admin_result,name='admin_result'),
    path('UnApprovedlist/',views.UnApprovedlist,name='UnApprovedlist'),
    path('UnApprovedlist/<int:num>/',views.admin_result,name='admin_result'),
    path('Approvedlist/',views.Approvedlist,name='Approvedlist'),
    path('Approvedlist/<int:num>/',views.admin_result,name='admin_result'),
    url(r'csvUpload/',views.csvUpload,name='csvUpload'),
    url(r'status',views.status,name='status'),


]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models
# Create your models here.

#Main "myapp" table which will contain title and description
class myapp(models.Model):
    title = models.CharField(max_length=100,default=' ')
    description = models.CharField(max_length=1000,default=' ')
    longitude=models.CharField(max_length=1000,default=0)
    latitude=models.CharField(max_length=1000,default=0)
    placetitle=models.CharField(max_length=1000,default= ' ')
    placetitle2=models.CharField(max_length=1000,default=' ')
    placetitle3=models.CharField(max_length=1000,default=' ')
    placetitle4=models.CharField(max_length=1000,default=' ')
    placevalue=models.CharField(max_length=1000,default=' ')
    placevalue2=models.CharField(max_length=1000,default=' ')
    placevalue3=models.CharField(max_length=1000,default=' ')
    placevalue4=models.CharField(max_length=1000,default=' ')

    class Meta:
        db_table = 'placeDb'

    def __str__(self):
        return self.title

#"imageLoc" Table which will store place_id frm "myapp" table and image with its status 
class imageLoc(models.Model):
    place_id = models.IntegerField()
    imageLocation = models.FileField(upload_to="images/",default=' ',blank = False)
    status = models.CharField(max_length = 1000 , default = " ")

    class Meta:
        db_table = 'imageDb'

    def __str__(self):
        return self.imageLocation

    #for ddleteing data from the file system
    def delete(self, *args, **kwargs):
        self.imageLocation.delete()
        super().delete(*args, **kwargs)


#"videoLoc" Table which will store place_id frm "myapp" table and video with its status 
class VideoLoc(models.Model):
    place_id = models.IntegerField()
    vedioLocation = models.FileField(upload_to="vedios/",default=' ',blank = False)
    status = models.CharField(max_length = 1000 , default = " ")

    class Meta:
        db_table = 'vedioDb'

    def __str__(self):
        return self.vedioLocation

    #for ddleteing data from the file system
    def delete(self, *args, **kwargs):
        self.vedioLocation.delete()
        super().delete(*args, **kwargs)

myapp/forms.py
from django import forms
from django.forms import ModelForm
from myapp.models import myapp


#Form to CSV file Updation
class UploadFileForm(forms.Form):
    file = forms.FileField(help_text='CSV fields should be in exact same order that is "title | description | imageLocation | vedioLocation " ')
    header = forms.BooleanField(label="Does CSV contain Header ?", required = False)
    title = forms.BooleanField(label="Does it contain title ?", required = False)
    description = forms.BooleanField(label="Does it contain description ?", required = False)
    latitude = forms.BooleanField(label="Does it contain latitude ?", required = False)
    longitude = forms.BooleanField(label="Does it contain longitude ?", required = False)

#Form to access myapp Model(DB) 
class myappForm(ModelForm):
    class Meta:
        model = myapp
        fields = ["title","description","latitude","longitude","placetitle","placevalue","placetitle2","placetitle3","placetitle4","placevalue2","placevalue3","placevalue4"]

#Form to Form Image and Video Uploading
class imgVDFileForm(forms.Form):
    place_id = forms.IntegerField()
    file = forms.FileField(help_text="select a image of vedio : ", required = False)
    img = forms.BooleanField(label="Is this a Image?", required = False)
    vdo = forms.BooleanField(label="Is this a Vedio?", required = False)


#Custom Login Form 
class LoginForm(forms.Form):
   username = forms.CharField(widget=forms.TextInput)
   password = forms.CharField(widget=forms.PasswordInput)

myapp/views.py
from django.shortcuts import render , render_to_response, redirect
from django.http import HttpResponse
from .models import myapp , imageLoc , VideoLoc
from django.views.decorators.csrf import csrf_exempt
from .forms import UploadFileForm , myappForm ,imgVDFileForm , LoginForm
from django.contrib.auth import authenticate, login
from django.http import JsonResponse
import pandas as pd
from django.forms import formset_factory
import json




# Create your views here.
#it will be called when adminpanel is requested
def index(request,message=""):
    #checking if the user is authenticated if yes rendering the page 
    if request.user.is_authenticated:
        message = "Welcome "+str(request.user.username)+" to Admin panel ..." if message == "" else message
        return render(request,'index.html', { "message" : message })            #rendering Adminpanel page
    
    #if user is not authenticated and its a POST request then it will take Login Form data and check for authentication  
    elif request.method =="POST":
        form = LoginForm(request.POST)     #loading Login form from the .forms in the top
        #checking the form passed is valid or not
        if form.is_valid():
            username=request.POST['username']
            password=request.POST['password']
            user = authenticate(request,username=username,password=password)           #getting user from given username and password if not found then it will return None
            #checking the authentication value if user existed it will give true 
            if user!=None and user.is_authenticated:
                login(request,user)        #login in the user to the django authenticaton system
                #rendering the admin panel
                message = "Welcome "+str(request.user.username)+" to Admin panel" if message == "" else message
                return render(request,'index.html', {"base":"adminpanel","message" : message})           #rendering Adminpanel page
    

        #if form is invalid it will ask for the login again
        form = LoginForm()                 #loading Login form from the .forms in the top
        message = "Please Enter a Valid Username & Password"
        return render(request,'registration/login.html',{"form":form,"message" : message})           #rendering Login page

    #if it is the GET request asking for login details
    else:
        form = LoginForm()                 #loading Login form from the .forms in the top
        message = "Please Login for Moving Further"
        return render(request,'registration/login.html',{"form":form,"message" : message})           #rendering Login page




# this is called when we have to "change" the image/Video status or To "delete" image or record     --- and is called by Result_script.js using AJAX 
def status(request):
    #Storing the new State from the signal state
    new_status = "Approved" if request.POST["status"] == "UnApproved" else "UnApproved" if request.POST["status"] == "Approved" else request.POST["status"]
    #this if will execute if the signal was of "Approved" or "unapproved"
    if new_status == "UnApproved" or new_status == "Approved":
        #checking the file type of the signal image
        if request.POST["file_type"] == "image":
            imgData = imageLoc.objects.get(id = int(request.POST["id"]))    #Fetching the data from the imageLoc table using "id" of the signal
            imgData.status = new_status    #updating the state
            imgData.save()
        #checking the file type of the signal video        
        else:
            vdoData = VideoLoc.objects.get(id = int(request.POST["id"]))   #Fetching the data from the VideoLoc table using "id" of the signal
            vdoData.status = new_status    #updating the state
            vdoData.save()

    #If the signal was of delete then
    elif request.POST["status"] == "Delete":
        #checking the file type of the signal --image
        if request.POST["file_type"] == "image":
            imgData = imageLoc.objects.get(id = int(request.POST["id"]))   #Fetching the data from the imageLoc table using "id" of the signal
            imgData.delete()                                               #deleting the data

        #checking the file type of the signal --vedio        
        elif request.POST["file_type"] == "video":
            vdoData = VideoLoc.objects.get(id = int(request.POST["id"]))   #Fetching the data from the VideoLoc table using "id" of the signal
            vdoData.delete()                                               #deleting the data

        #checking the file type of the signal --record        
        elif request.POST["file_type"] == "record":
            myappData = myapp.objects.get(id = int(request.POST["id"]))    #Fetching the data from the myapp table using "id" of the signal
            myappData.delete()                                             #deleting the data

            imgData = imageLoc.objects.filter(place_id = int(request.POST["id"]))   #Fetching the data from the imageLoc table using "id" of the signal
            for img_instance in imgData:                                            #deleting the all image dta
                img_instance.delete()
            vdoData = VideoLoc.objects.filter(place_id = int(request.POST["id"]))   #Fetching the data from the VideoLoc table using "id" of the signal
            for vdo_instance in vdoData:
                vdo_instance.delete()                                               #deleting the all video dta

    id = request.POST["id"]
    return JsonResponse({"file_type":request.POST["file_type"]})                    #sending the response to AJAX




#this will be called by admin_script.js using AJAX --- to get the result of the searched text in the adminpanel
def admin_search_titles(request):
    if request.method == 'POST':
        search_text = request.POST['search_text']
    else:
        search_text = ''
    #storing top "6" records containing that search text 
    articles = myapp.objects.filter(title__icontains=str(search_text))[:6]
    return render_to_response('admin_search.html',{'articles':articles})      # rendering results into admin panel 





#this is Called by the Unapprovied Tab from the navigation from the admin side
def UnApprovedlist(request):
    #checking for user authentication "only user can access these features"
    if request.user.is_authenticated:
        imgData = imageLoc.objects.filter(status = "UnApproved")         #collecting all unapproved images
        vdoData = VideoLoc.objects.filter(status = "UnApproved")         ##collecting all unapproved videos

        place_ids = list(set(int(entry.place_id) for entry in imgData))         #making a set of ids of these unapproved images
        place_ids_1 = list(set(int(entry.place_id) for entry in vdoData))       #making a set of ids of these unapproved video
        total_place_ids = list(set(place_ids + place_ids_1))                    #making set of all these images and video ids
        
        results = []
        for idx in total_place_ids:
            try:
                results.append(myapp.objects.get(id=idx))                        # storing data of all the unapproved ids
            except:
                continue

        message = "List of all the UnApproved Records."
        return render(request,"SelcetedList.html",{"results":results,"message":message})       #rendering the results in selectedlist.html with a message

    #if user is not authenticated ask for login 
    else:
        form = LoginForm()                         #login form 
        message = "Please Login for Moving Further"
        return render(request,'registration/login.html',{"form":form,"message" : message})     # rendering login page





#this is Called by the Approvied Tab from the navigation from the admin side
def Approvedlist(request):
    #checking for user authentication "only user can access these features"
    if request.user.is_authenticated:
        imgData = imageLoc.objects.filter(status = "Approved")           #collecting all approved images
        vdoData = VideoLoc.objects.filter(status = "Approved")           #collecting all approved videos

        place_ids = list(set(int(entry.place_id) for entry in imgData))         #making a set of ids of these approved images
        place_ids_1 = list(set(int(entry.place_id) for entry in vdoData))       #making a set of ids of these approved video
        total_place_ids = list(set(place_ids + place_ids_1))                    #making set of all these images and video ids
        
        results = []
        for idx in total_place_ids:
            try:
                results.append(myapp.objects.get(id=idx))                        # storing data of all the approved ids
            except:
                continue

        message = "List of all the Approved Records."
        return render(request,"SelcetedList.html",{"results":results,"message":message})         #rendering the results in selectedlist.html with a message

    #if user is not authenticated ask for login 
    else:
        form = LoginForm()                        #login form 
        message = "Please Login for Moving Further"
        return render(request,'registration/login.html',{"form":form,"message" : message})       # rendering login page



#this is Called by the All Data Tab from the navigation from the admin side
def AllDatalist(request):
    #checking for user authentication "only user can access these features"
    if request.user.is_authenticated:
        results = myapp.objects.filter()                                   # storing all the data 
        message = "List of all the Records."
        return render(request,"SelcetedList.html",{"results":results,"message":message})              #rendering the results in selectedlist.html with a message

    #if user is not authenticated ask for login 
    else:
        form = LoginForm()              #login form

myapp/templates/SelcetedList.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>

<body class="">
        <div class=""  style="background-color:#ffffff;">
                <nav class="navbar navbar-dark bg-transparent" style="height:60px;">
                    <a class="" href="/" style="border: 2px;">
                        <button class="btn btn-sm btn-outline-primary admin-header-button"
                        style="border-radius: 6%; padding: 0 15px;"
                            type="submit">
                            <h3>Home</h3>
                        </button></a>
                  
                    <a class="" href="/AllDatalist/" style="border: 2px;">
                        <button class="btn btn-sm btn-outline-primary"
                        style="border-radius: 6%; padding: 0 15px;" 
                        type="submit">
                            <h3>All Data Cards</h3>
                        </button></a>
                    <a class="" href="/Approvedlist/" style="border: 2px;">
                        <button class="btn btn-sm btn-outline-primary"
                        style="border-radius: 6%; padding: 0 15px;"
                            type="submit">
                            <h3>Approved Cards</h3>
                        </button></a>
                    <a class="" href="/UnApprovedlist/" style="border: 2px;">
                        <button
                        style="border-radius: 6%; padding: 0 15px;"
                            class="btn btn-sm btn-outline-primary" type="submit">
                            <h3>UnApproved Cards</h3>
                        </button></a>
                    <a class="" href="/adminpanel/0/" style="border: 2px;">
                        <button class="btn btn-sm btn-outline-primary"
                        style="border-radius: 6%; padding: 0 15px;"
                        type="submit">
                            <h3>Add Place</h3>
                        </button></a>
                    <a class="" href="/csvUpload/" style="border: 2px;">
                        <button class="btn btn-sm btn-outline-primary"
                        style="border-radius: 6%; padding: 0 15px;"
                            type="submit">
                            <h3>Upload CSV</h3>
                        </button></a>
                    <a class="" href="/admin/logout/" style="border: 2px;">
                        <button class="btn btn-sm btn-outline-primary"
                        style="border-radius: 6%; padding: 0 15px;"
                            type="submit">
                            <h3>Logout</h3>
                        </button></a>
                </nav>
        
                <div class="alert alert-info container" style="text-align: center;width: max-content;height: max-content;">
                    <strong>{{ message }}</strong>
                </div>
            </div>
    <div class="row">
        <div class="col-12" style="width:100%;color: black;text-align: left;">
            <ul id='search-results'>
                {% for result in results %}
                <div class="" style="padding: 20px; float: left; ">
                    <div class="card" style="width: 18rem;min-height: 350px;border-radius: 15px!important;
                    border-top-left-radius: 15px !important;
                    border-top-right-radius: 15px !important;
                    border-bottom-right-radius: 15px !important;
                    border-bottom-left-radius: 15px !important;
                    box-shadow: 0 6px 16px 0 rgba(0,0,0,.15),0 6px 16px 0 rgba(0,0,0,.12)!important;">
                        <!-- <img class="card-img-top" src="..." alt="Card image cap"> -->
                        <div class="card-body"
                            style="height: 100%;">
                            <h5 class="card-title">{{ result.title }}</h5>
                            <p class="card-text" style="height: 200px;overflow-x: auto;">{{ result.description }}</p>
                            <!-- <div style="height: 120px;" class="col">
                                    <img src="images/not_image.jpg" height="100" width="100" style="float: left;">
                                    <img src="images/not_image.jpg" height="100" width="100" style="float: right;">
                            </div> -->
                            <div class="" style="position: absolute;right: 20px;bottom: 20px;">
                                <a href="{{ result.id }}/" class="btn btn-primary">Explore more</a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </ul>
        </div>
    </div>
</body>

</html>

myapp/templates/admin_search.html
{% block content %}
{% for article in articles %}
<div class="" style="padding: 20px; float: left;">
    <div class="card" style="width: 20rem;min-height: 200px">
        <!-- <img class="card-img-top" src="/static/images/imagedefault.jpg" alt="Card image cap"> -->
        <div class="card-body" style="height: 100%;">
            <h5 class="card-title">{{ article.title }}</h5>
            <p class="card-text">{{ article.description }} </p>
            <div class="" style="position: absolute;right: 20px;bottom: 20px;">
                <a href="adminpanel/{{ article.id }}/" class="btn btn-primary">Explore more</a>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

myapp/templates/search_result.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Place</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
    <div class="conatiner" style="">
        <form method="POST" action="{% url 'add_image_data' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="conatiner" style="width: 100% ;padding-left:10%;padding-right:10%;padding-top:5%; ">
                <div class="row" style="background-color: aquamarine;padding: 50px">
                    <div class="col-1"></div>
                    <div class="col-5">
                        <div class="row">
                            <div class="col-12">
                                <input type="hidden" id="id_place_id" name="place_id" value={{ res.data.id }}></input>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <p>
                                    <b> Title :</b> {{ res.data.title }}
                                </p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <p>
                                    <b>Description :</b> 
                                    <textarea name="description">{{ res.data.description  }}</textarea>
                                </p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <div class="button-container">
                                    <a style="text-decoration: none" href="{% url 'home' %}">
                                        <input type="button" class="button" value="Go back"></input>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="row">
                            <div class="col-12">
                                <!-- {{ res.form.as_ul }} -->
                                {{ res.form.non_field_errors }}
                                <div class="row">
                                    <div class="fieldWrapper">
                                        {{ res.form.file.errors }}
                                        <label for="{{ res.form.file.id_for_label }}">Choose Image/Vedio :</label>
                                        {{ res.form.file }}
                                        {{ res.form.help_text }}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="fieldWrapper">
                                        {{ res.form.img.errors }}
                                        <label for="{{ res.form.img.id_for_label }}">Is this a Image ?:</label>
                                        {{ res.form.img }}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="fieldWrapper">
                                        {{ res.form.vdo.errors }}
                                        <label for="{{ res.form.vdo.id_for_label }}">Is this a Vedio ?</label>
                                        {{ res.form.vdo }}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <input type="submit">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="alert alert-info" style="text-align: center;">
                    <strong>{{ res.message }}</strong>
                </div>
            </div>


            <div class="">
                <div class="row">
                    <div class="col-1"></div>
                    <div class="col-10 conatiner">
                        <div class="" style="width:100%;">
                            <div id=''>
                                {% for imgvalues in res.imgData %}
                                <div class="" style="padding: 20px; float: left;">
                                    <div class="card"
                                        style="width: 18rem;height: 300px;border-radius: 50px;background-color: lightgrey">
                                        <div class="" style="height: 280px;">
                                            <a href="/static/media/{{ imgvalues.imageLocation  }}">
                                                <img class="card-img-top"
                                                    src="/static/media/{{ imgvalues.imageLocation  }}"
                                                    alt="Card image cap" style="height:100%;border-radius: 50px;">
                                            </a>
                                        </div>
                                        <div class="card-body" style="text-align: center;padding: 3px;">
                                            <h5 class="card-title">{{ imgvalues.status }}</h5>
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <div class="col-1"></div>
                </div>
            </div>

            <div class="">
                <div class="row">
                    <div class="col-1"></div>
                    <div class="col-10 conatiner">
                        <div class="" style="width:100%;">
                            <div id=''>
                                {% for vdovalues in res.vdoData %}
                                <div class="" style="padding: 20px; float: left;">
                                    <div class="card"
                                        style="width: 18rem;height: 300px;border-radius: 50px;background-color: lightgrey">
                                        <div class="" style="height: 280px;">
                                            <video class="card-img-top" controls
                                                src="/static/media/{{ vdovalues.vedioLocation  }}" alt="Card image cap"
                                                style="height:100%;border-radius: 50px;"></video>
                                        </div>
                                        <div class="card-body" style="text-align: center;padding: 3px;">
                                            <h5 class="card-title">{{ vdovalues.status }}</h5>
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <div class="col-1"></div>
                </div>
            </div>
        </form>
    </div>

</body>

</html>